apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kkamdung/order-service/k8s?ref=main

patches:
  - path: patch-env.yml

configMapGenerator:
  - name: order-config
    behavior: merge
    files:
      - application-staging.yml

images:
  - name: order-service
    newName: ghcr.io/kkamdung/order-service
    newTag: latest

replicas:
  - name: order-service
    count: 1
