apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kkamdung/catalog-service/k8s?ref=main

patches:
  - path: patch-env.yml

configMapGenerator:
  - name: catalog-config
  - behavior: merge
    files:
      - application-staging.yml

images:
  - name: catalog-service
    newName: ghcr.io/kkamdung/catalog-service
    newTag: latest
